#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLOT_PADDING 2
#define EPSILON 1e-6
#define RECORDER_INITIAL_CAPACITY 1024
#define CC_MINCUT_BIGDOUBLE   (1e30)
#define CC_MINCUT_ONE_EPSILON (0.000001)
#endif //CONSTANTS_H
