#ifndef ENUMS_H
#define ENUMS_H

typedef enum
{
    PARSE_SUCCESS,
    PARSE_IGNORED,
    PARSE_UNKNOWN_ARG,
    PARSE_USAGE_ERROR,
    PARSE_WRONG_VALUE_TYPE,
    PARSE_MISSING_VALUE,
    PARSE_MISSING_MANDATORY_FLAG
} ParsingResult;

typedef enum
{
    DUPLICATED_ENTRY,
    UNINITIALIZED_ENTRY,
    NON_MATCHING_COST,
    FEASIBLE,
} FeasibilityResult;

#define ENUM_TO_STRING(x) #x

#endif // ENUMS_H
